platform :ios, '10.2'
target 'MemeMe' do
  pod 'RealmSwift', '~> 2.4.3'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end
